name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
      env:
        NODE_VERSION: 18.17.0 # renovate: datasource=npm depName=node versioning=node
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Lint
      run: npm run lint --if-present
    - name: Check formatting
      run: npm run check-format --if-present
    - name: Run tests
      run: npm test
    - name: Build project
      run: npm run build --if-present
